### ISSUE TITLE
\section* is broken

### ISSUE THREAD

**Issue by bminemy1** [XimeraProject/ximeraLatex#12]
Thanks for the help buddy

**Comment by bartsnapp** [comment]
Currently this is broken.

However the default for \section is not to number. To turn on numbers use

\documentclass[numbers]{ximera}

I would like to get this fixed sometime though.... (whatever that means)

**Comment by bartsnapp** [comment]
Reiterating: 

However the default for \section is not to number. To turn on numbers use

\documentclass[numbers]{ximera}

this should be documented....
