### ISSUE TITLE
First paragraph in an activity not put in <p> tags

### ISSUE THREAD

**Issue by nbloomf** [XimeraProject/ximeraLatex#18]
Possible tex4ht bug: The first paragraph in an activity is not wrapped in p tags (or any tags) as all other paragraphs are. An example is at 

http://497a6980.ngrok.com/course/nbloomf/CollegeAlgebra/master/FirstParagraph

(View source and check out the paragraphs.)

However, this behavior is _not_ observed if the activity is started with a \section.

**Comment by bartsnapp** [comment]
Closing. I believe this is fixed.
