### ISSUE TITLE
sageCell doesn't allow for < symbol

### ISSUE THREAD

**Issue by mthomas7** [XimeraProject/ximeraLatex#42]
Putting a < in a sage cell causes problems rendering, though > is fine. Seems to be a problem with the way it's interpreting as html. Adds and extra <="" script=""/> at the end of the sageCell window.

Example:
\begin{sageCell}
c = 3/ln(4)
a = 1
b = 4
(c>a) and (b<c)
\end{sageCell}

**Comment by kisonecat** [comment]
This should be fixed by using CDATA in the appropriate place.

**Comment by bartsnapp** [comment]
I believe this to be fixed
