### ISSUE TITLE
Ability to change links in the footer

### ISSUE THREAD

**Issue by mthomas7** [XimeraProject/ximeraLatex#44]
The links in the footer direct to the OSU courses - if we're using ximera in, e.g. a calc 1 course, students might click that link thinking that it's the same calc 1 course. Either removing those links or replacing them with other links could help avoid confusion.

**Comment by bartsnapp** [comment]
Several people have asked for this. 
* We could remove it
* We could direct to a list of courses with institution. This opens a new can of worms. What *is* a course? I suppose a course is anything that an "instructor" says tells us is a course. I wonder if we could have a web-form that would allow people to add their own courses, with institution and a short description.

**Comment by mthomas7** [comment]
I could see the second option working nicely, though it seems like it might be a lot to keep track of. Maybe this would be easier to maintain if (eventually) people are hosting their own version, so each hosted version could have their own footer? And maybe in the meantime, it could either be removed or have the option (somehow) to be removed? Maybe some command in a xourse file?

**Comment by bartsnapp** [comment]
Will be fixed with ximera.org
