### ISSUE TITLE
Ability to change formatting of xourse page

### ISSUE THREAD

**Issue by mthomas7** [XimeraProject/ximeraLatex#45]
It could be nice to be able to change some of the formatting on the xourse page, e.g. centering \part boxes, maybe changing font color, etc.

**Comment by mthomas7** [comment]
Another suggestion that's been passed along to me is the ability to add different backgrounds to the boxes in the xourse page (something like a preview of what's in the lesson).

**Comment by kisonecat** [comment]
Hello,

> Another suggestion that's been passed along to me is the ability to add
> different backgrounds to the boxes in the xourse page (something like a
> preview of what's in the lesson).
>
Right now, the background of the box should be a faded out version of the
first image that appears in the activity.

What sort of background are you imagining?  Or the ability to change the
color?

~jim

**Comment by mthomas7** [comment]
Ah - the pages I've made are all just videos, so no image actually shows up (http://ximera.osu.edu/course/mthomas7/aaronVid/). Is it possible to direct the background to an image which doesn't actually show up in the section itself?

**Comment by kisonecat** [comment]
Hello,

> Ah - the pages I've made are all just videos, so no image actually
> shows up (http://ximera.osu.edu/course/mthomas7/aaronVid/). Is it
> possible to direct the background to an image which doesn't actually
> show up in the section itself?

We could use the video thumbnail?

~jim

**Comment by mthomas7** [comment]
Sure, that would be great!

**Comment by bartsnapp** [comment]
This should be done with a custom *.sty file
