### ISSUE TITLE
using factorials/binomial in the answer box

### ISSUE THREAD

**Issue by oguzkurt** [XimeraProject/ximeraLatex#53]
When a problem has `100!/30!` as an answer, the system accepts it. But if the outcome gets larger, the system does not accept it. Can you give me an idea as to how large an answer does the system accept. 

I personally like to write problems whose answers are large so that they will not be tempted to find the answer via calculator. Instead they will use the parsing ability within the answer box! This forces them to think in combinations and permutations. At least, I hope so!

**Comment by bartsnapp** [comment]
This is a server issue. I'll move the issue and close this one.
