### ISSUE TITLE
Symbolic answer

### ISSUE THREAD

**Issue by oguzkurt** [XimeraProject/ximeraLatex#55]
Hi folks,

I would like to have a symbolic answer to a problem.

Here is what I did?

```
\begin{sagesilent}
p=var('p')
k=var('k')
\end{sagesilent}
```
`$\answer{\sage{p}}$` worked fine!

`$\answer{\sage{p^k}}$` did not work!

interestingly, by mistake, I left `$\answer{\sage{p}}$` in the next problem but, this time, it did not work.

So, my questions are:

1. How do I make the symbolic input work?

2. Why does `$\answer{\sage{p}}$` work the first time and not the second time?
(I decided to enter sagesilent-part before each of the answers and try with it. It still did not work!) 

3. I care about using sage since I am also trying to have problems which will have factorials and binomials involved. any idea?

Thanks,
Oguz

**Comment by bartsnapp** [comment]
This is a server issue
