### ISSUE TITLE
tolerance=??

### ISSUE THREAD

**Issue by oguzkurt** [XimeraProject/ximeraLatex#57]
Hi folks,

What is the extremes of the `tolerance` in the `answer` environment. I tried something like `\answer[tolerance=0.0000001]` and it failed. In that case, the ? button does not work, nor does `ENTER`. When you click on the `?`, it actually refreshes the webpage.

Best,
Oguz

**Comment by kisonecat** [comment]
What is the content of the "\answer" parameter?  Is it a float?

**Comment by oguzkurt** [comment]
it is usually in

$$....
=\answer[tolerance=0.0000000001]{\sage{binomial(100,0)*0.01^0*0.99^100+binomial(100,1)*0.01^1*0.99^99+binomial(100,2)*0.01^2*0.99^98+binomial(100,3)*0.01^3*0.99^97}}$$
