### ISSUE TITLE
firstExample doesn't compile

### ISSUE THREAD

**Issue by siefkenj** [XimeraProject/ximeraLatex#59]
When trying to compile `firstExample/firstExample.tex` the following latex error occurs.

```
l.102 I
       n the plot below, is $P$ a function of $k$? [2]

! Attempt to use \answer outside of math mode.

See https://github.com/ximeraProject/ximeraLatex for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.137 The value of $P(2)$ is \answer{$2$}
```

I have tried both pdflatex and xelatex

**Comment by bartsnapp** [comment]
Hi,

Ah - our examples docs are a bit behind. I've just fixed them - you'll need to pull. 

They should compile now.

Also, currently ximera.cls has a bug involving the "wordChoice" environment. We'll be fixing this soon. 

To see more, definitely checkout:

http://ximera.osu.edu/course/XimeraProject/gettingStarted/

http://ximera.osu.edu/course/mooculus/calculus1

http://ximera.osu.edu/course/mooculus/calculus2

http://ximera.osu.edu/course/mooculus/calculus3

**Comment by bartsnapp** [comment]
New docs are found at: 
https://ximera.osu.edu/introduction
https://ximera.osu.edu/examples
