### ISSUE TITLE
\category{...}

### ISSUE THREAD

**Issue by kisonecat** [XimeraProject/ximeraLatex#76]
activities should be marked by their category, which could be lecture, homework, examples, problems, bonus problems, etc.

**Comment by bartsnapp** [comment]
XW6 can implement this... Though getting it spread throughout the system seems hard... Maybe we can write a script?

**Comment by bartsnapp** [comment]
Obsolete

**Comment by kisonecat** [comment]
I see -- I think I was perhaps thinking in terms of [CuratedCourses](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1505246).
