### ISSUE TITLE
Problem Structures

### ISSUE THREAD

**Issue by hparshall** [XimeraProject/ximeraLatex#8]
We need to decide on a basic supported problem structure that supports:
1. labeling in Ximera
2. multipart problems

For (1), it would be easiest to move to a single `problem` environment that mimics the behavior of the current `question`, `exploration`, and `exercise` environments.  I've implemented it.  The only difference between these environments is labeling, but this could be implemented by passing labeling options into the `problem` environment (which would be simple to do via the `enumitem` package).  

For (2), we discussed using the `enumerate` environment within a `problem`, but I've decided I'm against this.  `enumerate` is already implemented (in a logical fashion) in Ximera, and we'll want to use the data from parts of a problem in a different way than we will `enumerate` environments.  I've implemented a `parts` environment that mimics enumerate as far as LaTeX is concerned, but would ease labeling of parts and use of data from parts for Ximera.

My proposal would be the basic structure:

\begin{problem}
  Problem 1
\end{problem}
\begin{problem}
  Problem 2
  \begin{parts}
    Problem 2 (a)
    Problem 2 (b)
  \end{parts}
\end{problem}

I've come to agree with Bart that a "problems" list is a **bad** idea; each problem should be its own environment.

**Comment by bartsnapp** [comment]
This is now done with nesting
