### ISSUE TITLE
new environment request

### ISSUE THREAD

**Issue by annadavismath** [XimeraProject/ximeraLatex#84]
Hi Jim and Bart,

Could you create the following environments for the linear algebra project?

Exploration Problem 

Generalization

Historical Note

Thank you.
Anna

**Comment by bartsnapp** [comment]
Hi,

We already have "exploration"

And it's a problem-like environment.

Let me think about the rest

**Comment by bartsnapp** [comment]
https://ximera.osu.edu/demolition/demolition/textcolor/digInSecondFundamentalTheoremOfCalculus

how about this?

**Comment by annadavismath** [comment]
Bart,
Thank you for sending this.

Exploration is great, Remark is great.  I am not sure that we want the word Theorem to appear in Generalization.  Is there a way to remove the word Theorem?

Thanks!
Anna

**Comment by bartsnapp** [comment]
Hi!

I'd probably do

\paragraph{Generalization}

but any of these: 

could also go before it.

https://ximera.osu.edu/examples/exampleActivityCollection/theoremEnvironments/theoremEnvironments

**Comment by annadavismath** [comment]
This works.  Thanks!
Anna
